DROP TABLE IF EXISTS question3c;
CREATE TABLE question3c
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
AS
	SELECT Artist, COUNT(*) AS users
	FROM Streaming
	GROUP BY Artist
	HAVING users > 25000;

